### ISSUE TITLE
Q : Change "Query executed with no result set returned." to actually return how many rows were affected

### ISSUE THREAD

**Issue by SandorMatus** [halcyon-tech/vscode-db2i#101]
Hi
I have a question, is there any way to enable in the extension so it actually returns how many rows were affected i.e. using sql UPDATE in the ibm i results window. I was looking all over and could not find it in the extension settings. 

Thank you
Matt

**Comment by ThePrez** [comment]
Definitely feasible. Thanks for the suggestion!

**Comment by ThePrez** [comment]
I'll work on this once #93 is landed.

**Comment by SandorMatus** [comment]
Maybe saved you some time with #103, it's just a line edit in html.ts. I am using it in my own vscode and it works. 
You can close this issue.
