### ISSUE TITLE
Spinning up SQL job never ends

### ISSUE THREAD

**Issue by miattob** [halcyon-tech/vscode-db2i#109]
**Describe the bug**

No trace collection is available. After connecting to IBM i system, DB2 for i extension displays the message "Spinning up SQL job" which never ends. Checking SQL Job Manager shows no job in the list and only allows me to start a new one with the same result.

**To Reproduce**

1. Connect to IBM i system
2. Open DB2 for i extension
3. Expand SQL Job Manager and click on New SQL Job

**Expected behavior**

It is expected to connect to the system to run SQL statements.

**Screenshots**

![image](https://github.com/halcyon-tech/vscode-db2i/assets/41200818/3ff8b41d-8f21-420f-a216-2fc934c0fb30)

**Environment**

 - OS: Windows
 - Extension Version 0.4.0

**Comment by lgiammattei** [comment]
Same problem for me after latest update, here is the output from Db2 for i Server Component:

`{"status":200,"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.2.0","headers":{"accept-ranges":"bytes","access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","cache-control":"public, max-age=60, s-maxage=60","connection":"close","content-encoding":"gzip","content-length":"773","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Tue, 22 Aug 2023 10:37:32 GMT","etag":"W/\"a01eb59e931816be1db460fe96f868e17191e8187d9c0d21b4cf4a4a0b6ba5b3\"","last-modified":"Tue, 01 Aug 2023 13:06:04 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"GitHub.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept, Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-api-version-selected":"2022-11-28","x-github-media-type":"github.v3; format=json","x-github-request-id":"C90A:06E5:12947401:12C79FF5:64E48FEC","x-ratelimit-limit":"60","x-ratelimit-remaining":"56","x-ratelimit-reset":"1692701035","x-ratelimit-resource":"core","x-ratelimit-used":"4","x-xss-protection":"0"},"data":{"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108","assets_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108/assets","upload_url":"https://uploads.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108/assets{?name,label}","html_url":"https://github.com/ThePrez/CodeForIBMiServer/releases/tag/v1.2.0","id":114650108,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOGz1tIc4G1Wv8","tag_name":"v1.2.0","target_commitish":"main","name":"v1.2.0","draft":false,"prerelease":false,"created_at":"2023-08-01T13:05:10Z","published_at":"2023-08-01T13:06:03Z","assets":[{"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/assets/119591046","id":119591046,"node_id":"RA_kwDOGz1tIc4HINCG","name":"codeforiserver-1.2.0.jar","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/java-archive","state":"uploaded","size":332640,"download_count":369,"created_at":"2023-08-01T13:06:03Z","updated_at":"2023-08-01T13:06:04Z","browser_download_url":"https://github.com/ThePrez/CodeForIBMiServer/releases/download/v1.2.0/codeforiserver-1.2.0.jar"}],"tarball_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/tarball/v1.2.0","zipball_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/zipball/v1.2.0","body":""}}
`

**Comment by lgiammattei** [comment]
I've also tried to uninstall and re-install the extension but the issue is still there

**Comment by worksofliam** [comment]
@lgiammattei If you revert back to 2.0.2, does it work again?

**Comment by lgiammattei** [comment]
@worksofliam how do I revert to 2.0.2?

**Comment by worksofliam** [comment]
![](https://code.visualstudio.com/assets/docs/editor/extension-marketplace/uninstall-extension.png)

**Comment by lgiammattei** [comment]
I did it, it did not solve the issue 
![immagine](https://github.com/halcyon-tech/vscode-db2i/assets/54810977/a7605c61-5c2e-4453-8f2b-e8271173d0d8)
it's still spinning

**Comment by cwbuck** [comment]
FYI, had the same issue. I reverted to 0.3.0 and it's working for me now.

**Comment by worksofliam** [comment]
@cwbuck i thinks I managed to recreate it yesterday, but it looks to be just a UI bug. If you see it spinning on startup, but go to the Job Manager view, do you see a job?

**Comment by lgiammattei** [comment]
@cwbuck thank you, i reverted only the db2 for i extension and it's working again for me  too

**Comment by lgiammattei** [comment]
@worksofliam it is not only a problem of UI, when i tried to make a quary on a db table it doesn't work and there werre no job on the table manager

**Comment by cwbuck** [comment]
> @worksofliam it is not only a problem of UI, when i tried to make a quary on a db table it doesn't work and there werre no job on the table manager

Agreed. Same for me. No jobs appear on latest version.

**Comment by worksofliam** [comment]
When the job is spinning, are you able to share the output from the Db2 for i Server Component? It's found under the output tab.

**Comment by lgiammattei** [comment]
@worksofliam i shared mine on https://github.com/halcyon-tech/vscode-db2i/issues/109#issuecomment-1687945336

**Comment by worksofliam** [comment]
@lgiammattei And that was all of it? Usually I'd expect way more than that before the job even starts to spin up.

Thanks!

**Comment by cwbuck** [comment]
Here's mine
`{"status":200,"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/tags/v1.2.0","headers":{"accept-ranges":"bytes","access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","cache-control":"public, max-age=60, s-maxage=60","connection":"close","content-encoding":"gzip","content-length":"773","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Fri, 25 Aug 2023 12:52:09 GMT","etag":"W/\"5b7722b658ea8db67b6e1be88b059cb7f93bf865024f2b87794a71d6118dc38f\"","last-modified":"Tue, 01 Aug 2023 13:06:04 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"GitHub.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept, Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-api-version-selected":"2022-11-28","x-github-media-type":"github.v3; format=json","x-github-request-id":"EB22:6790:79FC21:FAC7B0:64E8A3F9","x-ratelimit-limit":"60","x-ratelimit-remaining":"40","x-ratelimit-reset":"1692968192","x-ratelimit-resource":"core","x-ratelimit-used":"20","x-xss-protection":"0"},"data":{"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108","assets_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108/assets","upload_url":"https://uploads.github.com/repos/ThePrez/CodeForIBMiServer/releases/114650108/assets{?name,label}","html_url":"https://github.com/ThePrez/CodeForIBMiServer/releases/tag/v1.2.0","id":114650108,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"node_id":"RE_kwDOGz1tIc4G1Wv8","tag_name":"v1.2.0","target_commitish":"main","name":"v1.2.0","draft":false,"prerelease":false,"created_at":"2023-08-01T13:05:10Z","published_at":"2023-08-01T13:06:03Z","assets":[{"url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/releases/assets/119591046","id":119591046,"node_id":"RA_kwDOGz1tIc4HINCG","name":"codeforiserver-1.2.0.jar","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/java-archive","state":"uploaded","size":332640,"download_count":623,"created_at":"2023-08-01T13:06:03Z","updated_at":"2023-08-01T13:06:04Z","browser_download_url":"https://github.com/ThePrez/CodeForIBMiServer/releases/download/v1.2.0/codeforiserver-1.2.0.jar"}],"tarball_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/tarball/v1.2.0","zipball_url":"https://api.github.com/repos/ThePrez/CodeForIBMiServer/zipball/v1.2.0","body":""}}`

**Comment by lgiammattei** [comment]
@cwbuck giving it a fast read your output seem exactly like mine

**Comment by worksofliam** [comment]
Do either of you see a notification about requiring an update to the server component?

**Comment by cwbuck** [comment]
yes, I get that each time I switch between v 0.4.0 (not working) and 0.3.0 (working)

**Comment by lgiammattei** [comment]
When reloading after installation of the 0.4.0 of the extension it asks also to update the server component. I refused to update but it hangs anyway

**Comment by lgiammattei** [comment]
@worksofliam FYI also 0.3.3 works like a charm

**Comment by worksofliam** [comment]
You folks probably should be accepting the required updates! I think this is mostly a UI bug on my end.

**Comment by ThePrez** [comment]
The updates are indeed required. The UI needs to handle the user rejection differently (by showing appropriate errors instead of hanging)

Can you verify whether it works if you accept the update?

**Comment by lgiammattei** [comment]
@ThePrez i've accepted the server component update but after this the extension does not work. 
To be clear: whether I accept the server side update or not 0.4.0 doesn't work on my PC

**Comment by cwbuck** [comment]
Exactly. I accept the update every time. 0.4.0 does not work regardless.

**Comment by worksofliam** [comment]
We have just released 0.4.1 to potentially solve the issue, and if not, please share the output again if it has additional info.

**Comment by cwbuck** [comment]
@worksofliam can confirm this is working for me after updating to 0.4.1!
