### ISSUE TITLE
Request for enhancements: export query results to csv or excel

### ISSUE THREAD

**Issue by lgiammattei** [halcyon-tech/vscode-db2i#114]
Hellò everybody. My request is not to report errors or problems but to propose an improvement of the extension, i.e. the possibility to export the results of queries executed through the extension in csv or excel format. Have you already considered this?

**Comment by worksofliam** [comment]
Hey, it's actually already possible for CSV and JSON.

Usually you'd run a query like this:

```sql
select * from department
```

And if you want CSV, you can do this:

```sql
csv: select * from department
```

You can replace `csv` with `json` to get JSON.

**Comment by WBSpmichal** [comment]
for the sake of better discoverability, would it be possible to add a button to the UI to just insert that line?
