### ISSUE TITLE
Delimited Object Names Are Not Handled Correctly

### ISSUE THREAD

**Issue by davecharron** [halcyon-tech/vscode-db2i#14]
### Problem
Working with schemas and objects that have delimited names is not currently possible due to the case folding done in the code.

Here is the view when attempting to work with a schema named `"TestDelimiters"`.  Note that the delimiters in the schema name are preserved, but the case within is not (it's folded to lowercase).  That error ripples down the tree, where the queries used to populate the lists fold the schema name to uppercase, resulting in no objects displayed, even though every sub-folder should have an item (see setup script below).
![image](https://github.com/halcyon-tech/vscode-db2i/assets/134640655/32cfdf34-2599-4adc-9edb-83e6b660d1f1)

### Catalogs and Name Columns

- Ordinary names are stored as uppercase values.
- Delimited names are stored with the case preserved but without the delimiting quotes.

Application code must be aware of these rules when querying the catalog files.

### Suggestion
The `QSYS2.DELIMIT_NAME` function can be used in the queries to properly delimit the name values being retrieved.
Example query that returns the table name `"Delimited Table"` with the correct case and delimiters.
```sql
SELECT QSYS2.DELIMIT_NAME(TABLE_NAME) FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'TestDelimiters' and TABLE_NAME = 'Delimited Table';
```

### Caveat
Changing the queries in `src\database\schemas.ts` to delimit the name values improves the front end as the Schema Browser will be able to list the various objects.  However, as the user drills deeper, to list table columns for example, the delimited name displayed must be de-delimited when plugged into the `QSYS2.SYSCOLUMNS` queries in `src\database\table.ts` or `src\database\view.ts`.

### Setup script
Here is a simple setup script to create a bunch of objects with delimited names.
``` sql
DROP SCHEMA "TestDelimiters";

CREATE SCHEMA "TestDelimiters";
  
CREATE TYPE "TestDelimiters"."Delimited Type" AS BIGINT;
  
CREATE TABLE "TestDelimiters"."Delimited Table" ("Delimited Column" INTEGER DEFAULT NULL, 
CONSTRAINT "TestDelimiters"."Delimited Key" PRIMARY KEY ("Delimited Column"));

CREATE INDEX "TestDelimiters"."Delimited Index" ON "TestDelimiters"."Delimited Table" ("Delimited Column" ASC);

CREATE TRIGGER "TestDelimiters"."Delimited Trigger" AFTER INSERT ON "TestDelimiters"."Delimited Table" 
FOR EACH ROW MODE DB2SQL BEGIN DECLARE X INT; END;

CREATE VIEW "TestDelimiters"."Delimited View" ("Delimited Column") AS SELECT * FROM "TestDelimiters"."Delimited Table";

CREATE ALIAS "TestDelimiters"."Delimited Alias" FOR "TestDelimiters"."Delimited Table";

CREATE FUNCTION "TestDelimiters"."Delimited Function" ("Delimited Parameter" INTEGER) 
RETURNS INTEGER LANGUAGE SQL BEGIN RETURN "Delimited Parameter"; END;

CREATE PROCEDURE "TestDelimiters"."Delimited Procedure" (INOUT "Delimited Parameter" INTEGER) 
LANGUAGE SQL BEGIN SET "Delimited Parameter" = 13; END;

CREATE VARIABLE "TestDelimiters"."Delimited Global Variable" BIGINT;
```

**Comment by worksofliam** [comment]
@davecharron I am working on fixing this and I've one into one last error. Can you explain to me why this query is returning 4 rows? I am expecting it to just return `delimited function`, but it's got `type` and `bigint` in there too.

```
select * from QSYS2.SYSFUNCS where ROUTINE_SCHEMA = 'TestDelimiters'  order by ROUTINE_NAME asc limit 501 
```

<img width="628" alt="image" src="https://github.com/halcyon-tech/vscode-db2i/assets/3708366/dc26effb-705c-4b6b-b16e-24aa1e51228d">

**Comment by davecharron** [comment]
@worksofliam weird.  System generated functions backing the user-defined distinct types.

add to your WHERE clause
``` sql
 and FUNCTION_ORIGIN = 'E'
```

[SYSFUNCS](https://www.ibm.com/docs/en/i/7.5?topic=views-sysfuncs)
<html><body>


FUNCTION_ORIGIN | ORIGIN | CHAR(1) | Identifies the type of function. If this is a procedure, this column contains a blank.   B  This is a built-in function (defined by Db2® for i).   E  This is a user-defined function.   U  This is a user-defined function that is based on another function.   S  This is a system-generated function.
-- | -- | -- | --



</body>
</html>
