### ISSUE TITLE
Option to allow results to appear in editor tabs

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-db2i#189]
Now that VS Code 1.85.1 allows for floating tabs or detaching tabs, would you consider moving the results back into an edit tab that I can then drag to a floating tab. 

Ideally, Each time you run a statement with this option to put the results into an edit tab, a new edit tab is created and filled with data.   One reason I don't often use the DB tool is that I like to run multiple queries and compare results side by side in ACS Run SQL Scripts.  If I was allowed to have the results go into a tab and each time the query is run a new tab is opened, I could use VS Codes compare features. 

Thanks for considering this. 

-Matt

**Comment by worksofliam** [comment]
Should be possible, but it'd be a very large change if we did. Let me consult with the team and get back to you.

**Comment by worksofliam** [comment]
Just merged this, not released yet!

**Comment by m-tyler** [comment]
Sweet.
