### ISSUE TITLE
Query Result Columns Too Wide

### ISSUE THREAD

**Issue by davecharron** [halcyon-tech/vscode-db2i#19]
When running a query, the results output column widths appear to be determined based on the column data itself.
In most cases the resulting display is acceptable.
### Problem
When the results include a column with a large length, the result columns end up rendering much wider than the view, making it impractical if not impossible to work with the data.
### Example
```sql
select * from qsys2.sysviews
```
The `SYSVIEWS` [catalog view](https://www.ibm.com/docs/en/i/7.5?topic=views-sysviews) includes as the 5th column the following:
<html><body>

VIEW_DEFINITION | TEXT | VARGRAPHIC(5000) CCSID 1200Nullable | The query expression portion of the CREATE VIEW statement. Contains the null value if the view definition cannot be contained in the column without truncation.
-- | -- | -- | --

</body>
</html>

In this screenshot it shows how only the first column of the results can be viewed.  The width of the data in the column is nominal, but the rendered width is excessive.  In order to view the second column one must scroll several pages to the right.  The larger the data in the column, the worse it gets.
![image](https://github.com/halcyon-tech/vscode-db2i/assets/134640655/6f889938-2b0b-4995-91c7-927221b489ec)

The relevant code would seem to be in [vscode-db2i/src/views/results/html.ts](https://github.com/halcyon-tech/vscode-db2i/blob/main/src/views/results/html.ts#L203)
``` javascript
style="min-width: max-content;"
```
Perhaps it should use a more conservative value for minimum width, and also set a maximum width so that the columns are no wider than the view itself.

**Comment by worksofliam** [comment]
This is a known issue with the UI toolkit. Hopefully to be resolved by end of July: https://github.com/microsoft/vscode-webview-ui-toolkit/issues/473#issuecomment-1516753890
