### ISSUE TITLE
Use of generateSQL does not check for active server and fails

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-db2i#82]
If user does not start the SQL JOB MANAGER then does a GENERATE SQL action a run error is returned. 
![image](https://github.com/halcyon-tech/vscode-db2i/assets/1353665/765351fa-b40a-44d3-9a5f-1b738c18208b)

**To Reproduce**

1. Stop or restart VS Code and do not start SQL JOB MANAGER.
2. Click on the DB2 for i view expand a schema
3. Expand any item type (like functions or tables), 
4. Right-Click on item and choose Generate SQL
5. Receive error `Number of host variables not valid. (07001)`
6. Open output channel `Code for IBM I :[serverid]` to see error

**Expected behavior**
To be told I need to start a SQL JOB MANAGER job or pop up to have me to just that. 

**Environment**

 - OS: [Windows 10]
 - Extension Version 0.3.2

**Additional context**
This is a medium priority issue, for me.

**Comment by ThePrez** [comment]
@m-tyler, are you able to download and evaluate the following test build?
https://github.com/halcyon-tech/vscode-db2i/suites/14527903392/artifacts/821801902

**Comment by m-tyler** [comment]
I did download and install extension, then updated the server component. 

![image](https://github.com/halcyon-tech/vscode-db2i/assets/1353665/52ce2997-1e04-45ca-8d4f-b9e119665752)

**Comment by ThePrez** [comment]
> 

Nice!! Does you `SET` statement work now as well?

**Comment by m-tyler** [comment]
Just updated to the newly released version and .  Thanks for getting to this so quickly.
