### ISSUE TITLE
issue with SQL set command

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-db2i#83]
**Describe the bug**
set `variable` = `value`; causes a java run time error

**To Reproduce**

1. Connect to SQL JOB MANAGER
2. Open any edit tab and make sure language is SQL
3. Create a variable if one does not exist to update, like `create or replace variable myvarible char(10);`
4. Key a set command like `set myvariable = 'ME';`
5. java error appears in `IBM i: Results` output channel. 

**Expected behavior**
Statement is run to completion.

**Screenshots**
![image](https://github.com/halcyon-tech/vscode-db2i/assets/1353665/70711381-b639-4184-966d-468725fa82dc)

**Environment**

 - OS: Windows 10.0
 - Extension Version 0.3.2

**Additional context**

This is a high priority for me.

**Comment by ThePrez** [comment]
Does the latest build you downloaded (from my comment in #82) fix this issue? 
(Sorry, I commented on the wrong issue, and meant to comment here rather than #82)

**Comment by m-tyler** [comment]
I had some troubles for some reason.  I reset the extension back, restarted VSC, connected, opened a SQL JOB, and tried again to get the problem (I did).  Then I loaded the version you passed on to me and restarted VSC.  I was able to run the sets commands successfully. 

![image](https://github.com/halcyon-tech/vscode-db2i/assets/1353665/5d782ac7-a06b-40c5-885d-76a7a1ee233c)
