### ISSUE TITLE
Error on the text statement created via "Generate SQL" option

### ISSUE THREAD

**Issue by lgiammattei** [halcyon-tech/vscode-db2i#89]
**Describe the bug**

When using "Generate SQL" option on view object the statement's text contains sintax error. Such name of field contain random blanks 

**To Reproduce**

Select a view, generate SQL and look at the text created

**Expected behavior**

Correct sintax in the statement

**Environment**

 - OS: Windows 10
 - Extension Version latest avaible when writing

**Additional context**
I enclose the generated wrong statement
CREATE
OR REPLACE VIEW LND_DW.R_STATIS (
  STAG1,
  STAG2,
  COMIT,
  SATSO,
  TOTST,
  SOCIE,
  ISCNA,
  ISCRE,
  ISCPO,
  ISC11M,
  ISC11F,
  ISC5M,
  ISC5F,
  ISCALM,
  ISCALM5,
  ISCALF,
  ISCALF5,
  ISCGIM,
  ISCGIM5,
  ISCGIF,
  ISCGIF5,
  ISCES,
  ISCPU,
  ISCPC,
  ISCPA,
  ATTC11M,
  ATTC11F,
  ATTC5M,
  ATTC5F,
  ATTC5MP,
  ATTC5FP,
  TOCAL,
  TOFEC,
  TOCA1,
  TOFE1,
  TOCA2,
  TOFE2,
  TOCA3,
  TOFE3,
  TOCA4,
  TOFE4,
  TOCA5,
  TOFE5,
  TOCA6,
  TOFE6,
  TOALL,
  TOMAS,
  TOMED,
  DIDRA,
  DIDIR,
  DIALL,
  DIMAS,
  DIALT
) AS (
  SELECT
    STAG1,
    STAG2,
    COMIT,
    SATSO,
    COUNT(SATSO) AS TOTST,
    COUNT(SOCIE) AS SOCIE,
    SUM (ISCNA) AS ISCNA,
    SUM(ISCRE) AS ISCRE,
    SUM(ISCPO) AS ISCPO,
    **SUM(I SC11M)** AS ISC11M,    
    SUM(ISC11F) AS ISC11F,
    SUM(ISC5M) AS ISC5M,
    SUM(ISC5F) AS **IS C5F,**      
    SUM(ISCALM) AS ISCALM,
    SUM(ISCALM5) AS ISCALM5,
    SUM(ISCALF) AS ISCALF,
    SUM(ISCALF5) AS ISCALF5,
    SUM(ISCGIM) AS ISCGIM,
    SUM(ISCGIM5) AS ISCGIM5,
    SUM(ISCGIF) AS ISCGIF,
    SUM(ISCGIF5) AS ISCGIF5,
    SUM(ISCES) AS ISCES,
    SUM(ISCPU) **A S** ISCPU,  
    SUM(ISCPC) AS ISCPC,
    SUM(ISCPA) AS ISCPA,
    SUM (SAT1M) AS ATTC11M,
    SUM (SAT1F) AS ATTC11F,
    SUM (SAT5M) AS ATTC5M,
    SUM (SAT5F) AS ATTC5F,
    **SU M** (SAT52) AS ATTC5MP,
    SUM(SAT53) AS ATTC5FP,
    SUM (TOCAL) AS TOCAL,
    SUM(TO FEC) AS TOFEC,
    SUM(TOCA1) AS TOCA1,
    SUM (TOFE1) AS TOFE1,
    SUM (TOCA2) AS TOCA2,
    SUM(TOFE2) AS TOFE2,
    SUM(TOCA3) AS TOCA3,
    SUM(TOFE3) AS TOFE3,
    SUM(TOCA4) AS TOCA4,
    SUM(TOFE4) AS TOFE4,
    SUM(TOCA5) AS TOCA5,
    SUM(TOFE5) AS TOFE5,
    SUM(**TOCA 6**) AS TOCA6,
    SUM(TOFE6) AS TOFE6,
    SUM(TOALL) AS TOALL,
    SUM(TOMAS) AS TOMAS,
    **S UM**(TOMED) AS TOMED,  
    SUM (DIDRA) AS DIDRA,
    SUM(DIDIR) AS DIDIR,
    SUM(DIALL) AS D IALL,
    SUM(DIMAS) AS DIMAS,
    SUM(DIALT) AS DIALT
  FROM
    LND_DW.STASOTES
  GROUP BY
    **STA G1**,
    STAG2,
    COMIT,
    SATSO
) RCDFMT R_STATIS;

**Comment by worksofliam** [comment]
Possible duplicate of #59

**Comment by lgiammattei** [comment]
Same error as #59 i close this issue
